<?php

return [
    'site_logo' => '/assets/frontend/dist/imgs/theme/logo.svg',
    'site_phone' => '+1 (555) 123-4567',
    'site_currency' => 'USD',
    'site_currency_icon' => '$',
    'site_copyright' => 'ShopX',
    'paypal_status' => env('PAYPAL_STATUS', 'inactive'),
    'paypal_mode' => env('PAYPAL_MODE', 'sandbox'),
    'paypal_currency' => env('PAYPAL_CURRENCY', 'USD'),
    'paypal_rate' => env('PAYPAL_RATE', 1),
    'paypal_client_id' => env('PAYPAL_CLIENT_ID', ''),
    'paypal_secret' => env('PAYPAL_SECRET', ''),
    'stripe_status' => env('STRIPE_STATUS', 'inactive'),
    'stripe_mode' => env('STRIPE_MODE', 'sandbox'),
    'stripe_currency' => env('STRIPE_CURRENCY', 'USD'),
    'stripe_rate' => env('STRIPE_RATE', 1),
    'stripe_key' => env('STRIPE_KEY', env('STRIPE_CLIENT_ID', '')),
    'stripe_secret' => env('STRIPE_SECRET', ''),
    'stripe_webhook_secret' => env('STRIPE_WEBHOOK_SECRET', ''),
    'razorpay_status' => env('RAZORPAY_STATUS', 'inactive'),
    'razorpay_currency' => env('RAZORPAY_CURRENCY', 'INR'),
    'razorpay_rate' => env('RAZORPAY_RATE', 1),
    'razorpay_client_id' => env('RAZORPAY_CLIENT_ID', ''),
    'razorpay_secret' => env('RAZORPAY_SECRET', ''),
];
